var tf2stars_css = [
    ".playerSlot .details { ",
    "   width: 195px; ",
    "} ",
    ".icons.stats.small { ",
    "   margin-right: 0px; ",
    "   margin-left: 0px; ",
    "} ",
    ".lobbySlot .gameStatusContainer { ",
    "   width: 65px; ",
    "} ",
    ".statsContainer span { ",
    "   margin-left: 0px; ",
    "   margin-right: 0px; ",
    "} ",
    "div.wicket-mask-dark { ",
    "opacity: 0; ",
    "} ",
    ".rating-static { ",
    "  width: 60px; ",
    "  height: 16px; ",
    "  display: block; ",
    "  background-image: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAHgAAAAgCAMAAADuZ0x6AAAAb1BMVEUAAAB4dm54dm7kbxtxcGffbhdhX1Z3dm3fcBB6eXB4dm7mbxp4dm7lbxp4dm7kbhp6eXDlbxrlbxp4dm7kbhvmbxnmbhl2dWzlbxvebxDlcBnjbxh6eXDmbxvlbxl6eXDkbxvDVjinTS/ncBt9fHPsGYAOAAAAI3RSTlMAbzAwICAQnhDw4ODPz7Cwr6+fkJBwb1DwEFBAwMBQQGD1nFcgBaAAAAENSURBVEjH7dXJbsJAEIThGu+YHQPGJCFLz/s/Y5TKIJPkQtclQlCnfy4tzenD/+5FbO5Z76Md5UYfe7m3tpUbXezkntpUbrSxlfpg5x3enI2PSTxvgouur2jk83Rnnrsb2SzdmWXuRrPhnU0Df6OqeaeuhEbJQyWURsFDhdQ7HtpJjcBDQeqlrcu1LaXGIq6KVVwo3dgewN4aoVHFwG9UQj/l+FpeXtW/Hq8ZOyvc/di9zGtwkDz+u5OdnN3LHnO6x53sMad73Koec4LH76m/efUaHDBO9Jik+j3+sSH5OniapAoGjxM9JqmKwWmyxyRVMThN9pikCgZfbki+Do4mqYLH4wSP2ST1YfBt7BPuIYVPT90lrgAAAABJRU5ErkJggg=='); ",
    "} ",
    ".rating-50 { background-position: 0 0; } ",
    ".rating-40 { background-position: -12px 0; }  ",
    ".rating-30 { background-position: -24px 0; } ",
    ".rating-20 { background-position: -36px 0; } ",
    ".rating-10 { background-position: -48px 0; } ",
    ".rating-0 { background-position: -60px 0; }  ",
    ".rating-5  { background-position: -48px -16px; } ",
    ".rating-15 { background-position: -36px -16px; } ",
    ".rating-25 { background-position: -24px -16px; } ",
    ".rating-35 { background-position: -12px -16px; } ",
    ".rating-45 { background-position: 0 -16px; } ",
    "a.rating {outline:none; } ",
    "a.rating strong {line-height:30px;} ",
    "a.rating:hover {text-decoration:none;}  ",
    "a.rating span.tooltip { ",
    "   z-index:10; ",
    "   display: none; ",
    "   padding: 14px 20px; ",
    "   margin-top: -30px; ",
    "   margin-left: 28px; ",
    "   width: 180px; ",
    "   opacity: 1; ",
    "} ",
    "a.rating:hover span.tooltip{ ",
    "   display:inline; ",
    "   position:absolute; ",
    "   text-align: left; ",
    "   color:#111; ",
    "   border:1px solid #DCA; ",
    "   background:#fffAF0; ",
    "} ",
    "p.motd { ",
    "   color: #7badba; ",
    "} ",
].join('\n');
